version: '3.7'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    hostname: mysql
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volume/conf/:/etc/mysql/conf.d/      
      - ./volume/data:/var/lib/mysql
      - ./volume/log:/var/log/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: image_board
      MYSQL_DATABASE: image_board
      MYSQL_USER: worker
      MYSQL_PASSWORD: d26N7MKLzlhk
    command: 
    - mysqld
    - --character-set-server=utf8
    - --collation-server=utf8mb4_unicode_ci
    - --character-set-server=utf8mb4
    ports:
      - 33306:3306